In [3]:
import pandas as pd
 
df = pd.read_csv(r'C:\Users\Dell\Downloads\bank_churn_master.csv')

In [4]:
df.head()

,customer_id,surname,credit_score,geography,gender,age,tenure,balance,num_of_products,has_cr_card,...,total_txn_amount,activity_decline_pct,complaint_count,last_complaint_date,has_creditcard,has_fixeddeposit,has_insurance,has_mutualfund,has_personalloan,has_savings
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,...,1356913.0,NaN,0,NaN,1.0,0.0,0.0,0.0,0.0,1.0
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,...,1801051.0,-1.8,0,NaN,0.0,0.0,0.0,0.0,0.0,1.0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,...,637305.0,74.5,0,NaN,1.0,1.0,0.0,1.0,0.0,1.0
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,...,697809.0,10.4,0,NaN,0.0,1.0,0.0,0.0,0.0,1.0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,...,2244888.0,-4.0,0,NaN,1.0,0.0,0.0,0.0,0.0,1.0

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 30 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           10000 non-null  int64
 1   surname               10000 non-null  str
 2   credit_score          10000 non-null  int64
 3   geography             10000 non-null  str
 4   gender                10000 non-null  str
 5   age                   10000 non-null  int64
 6   tenure                10000 non-null  int64
 7   balance               10000 non-null  float64
 8   num_of_products       10000 non-null  int64
 9   has_cr_card           10000 non-null  int64
 10  is_active_member      10000 non-null  int64
 11  estimated_salary      10000 non-null  float64
 12  exited                10000 non-null  int64
 13  zone                  10000 non-null  str
 14  signup_date           10000 non-null  str
 15  exit_date             2037 non-null   str
 16  deposit_target_cr     10000 non-null  int64
 17  rm_headcount          10000 non-null  int64
 18  baseline_avg_txns     10000 non-null  float64
 19  recent_avg_txns       8491 non-null   float64
 20  total_txn_amount      10000 non-null  float64
 21  activity_decline_pct  8491 non-null   float64
 22  complaint_count       10000 non-null  int64
 23  last_complaint_date   733 non-null    str
 24  has_creditcard        10000 non-null  float64
 25  has_fixeddeposit      10000 non-null  float64
 26  has_insurance         10000 non-null  float64
 27  has_mutualfund        10000 non-null  float64
 28  has_personalloan      10000 non-null  float64
 29  has_savings           10000 non-null  float64
dtypes: float64(12), int64(11), str(7)
memory usage: 2.3 MB

In [7]:
df.describe(include='all')

,customer_id,surname,credit_score,geography,gender,age,tenure,balance,num_of_products,has_cr_card,...,total_txn_amount,activity_decline_pct,complaint_count,last_complaint_date,has_creditcard,has_fixeddeposit,has_insurance,has_mutualfund,has_personalloan,has_savings
count,1.000000e+04,10000,10000.000000,10000,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,...,1.000000e+04,8491.00000,10000.000000,733,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0
unique,NaN,2932,NaN,3,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,431,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,Smith,NaN,France,Male,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2025-08-13,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,32,NaN,5014,5457,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN
mean,1.569094e+07,NaN,650.528800,NaN,NaN,38.921800,5.012800,76485.889288,1.530200,0.70550,...,1.238816e+06,5.63976,0.145800,NaN,0.70550,0.136300,0.133400,0.128200,0.132300,1.0
std,7.193619e+04,NaN,96.653299,NaN,NaN,10.487806,2.892174,62397.405202,0.581654,0.45584,...,7.858380e+05,25.08285,0.563892,NaN,0.45584,0.343124,0.340024,0.334329,0.338834,0.0
min,1.556570e+07,NaN,350.000000,NaN,NaN,18.000000,0.000000,0.000000,1.000000,0.00000,...,7.484900e+04,-122.20000,0.000000,NaN,0.00000,0.000000,0.000000,0.000000,0.000000,1.0
25%,1.562853e+07,NaN,584.000000,NaN,NaN,32.000000,3.000000,0.000000,1.000000,0.00000,...,5.340168e+05,-4.30000,0.000000,NaN,0.00000,0.000000,0.000000,0.000000,0.000000,1.0
50%,1.569074e+07,NaN,652.000000,NaN,NaN,37.000000,5.000000,97198.540000,1.000000,1.00000,...,1.045033e+06,0.70000,0.000000,NaN,1.00000,0.000000,0.000000,0.000000,0.000000,1.0
75%,1.575323e+07,NaN,718.000000,NaN,NaN,44.000000,7.000000,127644.240000,2.000000,1.00000,...,1.904780e+06,6.20000,0.000000,NaN,1.00000,0.000000,0.000000,0.000000,0.000000,1.0
max,1.581569e+07,NaN,850.000000,NaN,NaN,92.000000,10.000000,250898.090000,4.000000,1.00000,...,3.972859e+06,100.00000,3.000000,NaN,1.00000,1.000000,1.000000,1.000000,1.000000,1.0

In [8]:
df.isnull().sum()

customer_id                0
surname                    0
credit_score               0
geography                  0
gender                     0
age                        0
tenure                     0
balance                    0
num_of_products            0
has_cr_card                0
is_active_member           0
estimated_salary           0
exited                     0
zone                       0
signup_date                0
exit_date               7963
deposit_target_cr          0
rm_headcount               0
baseline_avg_txns          0
recent_avg_txns         1509
total_txn_amount           0
activity_decline_pct    1509
complaint_count            0
last_complaint_date     9267
has_creditcard             0
has_fixeddeposit           0
has_insurance              0
has_mutualfund             0
has_personalloan           0
has_savings                0
dtype: int64

In [10]:
df["exit_date"] = pd.to_datetime(df["exit_date"])            # NaT = still active
df["signup_date"] = pd.to_datetime(df["signup_date"])
df["last_complaint_date"] = pd.to_datetime(df["last_complaint_date"])
 
df["recent_avg_txns"] = df["recent_avg_txns"].fillna(0)      # exited: no recent txns
df["activity_decline_pct"] = df["activity_decline_pct"].fillna(100)  # full stop = 100% decline
df["has_complained"] = df["complaint_count"].gt(0).astype(int) 
df.isnull().sum()      # cleaner flag

customer_id                0
surname                    0
credit_score               0
geography                  0
gender                     0
age                        0
tenure                     0
balance                    0
num_of_products            0
has_cr_card                0
is_active_member           0
estimated_salary           0
exited                     0
zone                       0
signup_date                0
exit_date               7963
deposit_target_cr          0
rm_headcount               0
baseline_avg_txns          0
recent_avg_txns            0
total_txn_amount           0
activity_decline_pct       0
complaint_count            0
last_complaint_date     9267
has_creditcard             0
has_fixeddeposit           0
has_insurance              0
has_mutualfund             0
has_personalloan           0
has_savings                0
has_complained             0
dtype: int64

In [13]:
#Duplicates & Validity
df["customer_id"].duplicated().sum()
df.duplicated().sum()
((df.age < 18) | (df.age > 100)).sum()
(df.balance < 0).sum()
bad_exit = ((df.exited == 1) & df.exit_date.isna()).sum() + \
           ((df.exited == 0) & df.exit_date.notna()).sum()
#Logical consistency check — my favorite. & means AND. Two impossible
#combinations: (churned AND no exit date) + (active AND has exit date).
#Both counts should be 0. The \ just continues the line.
#This checks whether columns agree with each other — a step most
#beginners skip and interviewers love.

In [15]:
 #Standardisation & New Features
df["gender"] = df["gender"].str.strip().str.title()
df["age_band"] = pd.cut(df.age, bins=[17, 30, 40, 50, 60, 200],
                        labels=["18-30", "31-40", "41-50", "51-60", "60+"])
df["balance_lakh"] = (df.balance / 1e5).round(2)
df["is_zero_balance"] = (df.balance == 0).astype(int)
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace('  ','_')

In [16]:
df.columns

Index(['customer_id', 'surname', 'credit_score', 'geography', 'gender', 'age',
       'tenure', 'balance', 'num_of_products', 'has_cr_card',
       'is_active_member', 'estimated_salary', 'exited', 'zone', 'signup_date',
       'exit_date', 'deposit_target_cr', 'rm_headcount', 'baseline_avg_txns',
       'recent_avg_txns', 'total_txn_amount', 'activity_decline_pct',
       'complaint_count', 'last_complaint_date', 'has_creditcard',
       'has_fixeddeposit', 'has_insurance', 'has_mutualfund',
       'has_personalloan', 'has_savings', 'has_complained', 'age_band',
       'balance_lakh', 'is_zero_balance'],
      dtype='str')

In [19]:
pip install pandas sqlalchemy pyodbc

Requirement already satisfied: pandas in c:\users\dell\appdata\local\python\pythoncore-3.14-64\lib\site-packages (3.0.3)
Requirement already satisfied: sqlalchemy in c:\users\dell\appdata\local\python\pythoncore-3.14-64\lib\site-packages (2.0.51)
Collecting pyodbc
  Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\users\dell\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\dell\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: greenlet>=1 in c:\users\dell\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from sqlalchemy) (3.5.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dell\appdata\local\python\pythoncore-3.14-64\lib\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pyodbc-5.3.0-cp314-cp314-win_amd64.whl (72 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
import os
os.chdir(r"C:\Users\Dell\Downloads\bank-customer-churn-analysis-final\bank-customer-churn-analysis")
print(os.listdir())   # should now show: data, ingestion, scripts, docs, dashboard...
!python ingestion/load_data.py

['dashboard', 'data', 'docs', 'ingestion', 'python_analysis', 'README.md', 'requirements.txt', 'scripts']

2026-07-12 23:17:36,599 | INFO | Reading Bank_Churn.csv
2026-07-12 23:17:36,625 | INFO | Loaded 10,000 rows x 14 columns
2026-07-12 23:17:36,643 | INFO | check | duplicate CustomerId                : 0
2026-07-12 23:17:36,643 | INFO | check | fully duplicated rows               : 0
2026-07-12 23:17:36,644 | INFO | check | null values (total)                 : 0
2026-07-12 23:17:36,644 | INFO | check | age out of range (<18 or >100)      : 0
2026-07-12 23:17:36,644 | INFO | check | negative balance                    : 0
2026-07-12 23:17:36,644 | INFO | check | Exited outside {0,1}                : 0
2026-07-12 23:17:36,644 | INFO | check | unexpected Geography values         : 0
2026-07-12 23:17:36,644 | INFO | note  | zero-balance customers          : 36.0% (documented in data_issues_log.md)
2026-07-12 23:17:36,931 | INFO | Wrote table 'customers' (10,000 rows) -> sqlite:///C:\Users\Dell\Downloads\bank-customer-churn-analysis-final\bank-customer-churn-analysis\bank_churn.db
2026-07-12 23:17:36,931 | INFO | Ingestion complete.

In [26]:
df.to_csv("data/bank_churn_master_clean.csv", index=False)
import os
[f for f in os.listdir("data") if "master" in f]

['bank_churn_master.csv', 'bank_churn_master_clean.csv', 'build_master_csv.py']

In [27]:
import pandas as pd
from sqlalchemy import create_engine

ENGINE_URL = (
    "mssql+pyodbc://@localhost\\SQLEXPRESS01/bank_churn"
    "?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)
engine = create_engine(ENGINE_URL)

df = pd.read_csv("data/bank_churn_master_clean.csv")
df.to_sql("customers", engine, if_exists="replace", index=False)
print(f"Loaded {len(df):,} rows x {df.shape[1]} columns into SQL Server")

Loaded 10,000 rows x 34 columns into SQL Server